### ISSUE TITLE
Compiling Hypre for GPU

### ISSUE THREAD

**Issue by mcytowski** [LLNL/hypre#26]
Hi,

I am trying to compile Hypre for GPU on sles12sp2 with GNU compilers, OpenMPI and CUDA 8.0 (and 9.0 as well). I have also tried to compile it with PGI and Intel. I always end up with some problems related to c++11 compatibility, extended-lambda or others.. (depends on the compiler I am currently using). Also, running "./configure --with-MPI --with-cuda --with-nvcc --enable-unified-memory" results in producing not working Makefile.
Is GPU compilation already supported? Could you please give me some advices, at least which versions of which compilers and CUDA should I try? Should I use clang?

Kind regards,
Maciej

**Comment by ulrikeyang** [comment]
Hello Maciej,

The hypre GPU version is currently meant for ‘friendly users’ only since it still has a lot of issues. We have used it here mainly with IBM’s xlc compiler. There have also been successes using it with clang. It does require c++11 compatibility due to the lambdas. We are still working on improving it.
On which machine are you trying to run it, and which solvers and interfaces are you trying to use?
I hope that some of the hypre developers who are actively working on this will also respond to your questions.

Regards
Ulrike

**Comment by mcytowski** [comment]
Hi Ulrike,

I am using SStruct interface, CSRPCG and BoomerAMG. The system I am trying to compile for is Pawsey's Athena GPU: https://support.pawsey.org.au/documentation/display/US/Athena+User+Guide 

I was actually looking at clang already, but I was not sure if this is a good path. I will follow this path and see how it goes. 

Thank you!
Maciej

**Comment by jeanlucf22** [comment]
I was able to build hypre on OLCF Summitdev using the nvcc compiler, with xlc as host compiler:
module load xl
./configure --with-cuda --enable-unified-memory --with-nvcc

I am using the struct solver with PFMG, on a single node (4 MPI tasks for 4 GPUs). I am seeing some issues at run time though, such as a much higher number of iterations when the mesh gets large:
struct -n 64 32 32 -P 1 2 2 -solver 1 -> 17 iterations to converge
struct -n 128 64 64 -P 1 2 2 -solver 1 -> 61 iterations
Is it a know issue?
I also get CUDA errors (illegal memory access) for larger meshes.

Jean-Luc

**Comment by liruipeng** [comment]
Hi, Jean-Luc,

We are going to have a new GPU release of hypre soon, which is under testing and reviewing. Running the above two problems in your last message with the new code, it seemed that the problem is gone: both converged in 17 iterations. So probably there were some issues in the last release. I ran cuda-memcheck with the larger problem. Also seemed OK.

Thank you for report this to us

Regards

-Ruipeng

**Comment by jeanlucf22** [comment]
I just installed the latest release (2.14.0) and can confirm that the problem is fixed. I can successfully run the 'struct' driver and get near-constant number of iterations and non-crashing runs.
Thanks!
Jean-Luc

**Comment by liruipeng** [comment]
Glad to see this!

Thank you!

-Ruipeng
