### ISSUE TITLE
1D bug for struct solver?

### ISSUE THREAD

**Issue by jeanlucf22** [LLNL/hypre#34]
Hi all,

I ran into an issue while trying to run a 1D test problem using the struct SMG or PFMG hypre solvers. It leads to a segfault for me. To figure out if I was doing something wrong, I tried running the test driver "struct" and also got a segfault:
aprun -n1 ./struct -d 1
It looks like there is hypre support for 1D problems. I am assuming it is not used much, so it may have gone unnoticed... In my case, running in 1D is useful to verify my code in some regimes. 
I tried running through a debugger, and it looks like it fails when constructing the coarse grid operator.

Jean-Luc Fattebert

**Comment by rfalgout** [comment]
Hi Jean-Luc,

I don't think SMG or PFMG have ever worked for 1D problems (not 100 percent sure, though).  In either case, 1D should amount to simply calling cyclic reduction.  At some point, we could add that test/branch to the SMG/PFMG codes, but for now you can just call it directly yourself.  The interface for cyclic reduction is very similar to either SMG or PFMG (even simpler because there are almost no parameters).

Hope this helps.

-Rob

**Comment by jeanlucf22** [comment]
Works for me, thanks Rob!
