### ISSUE TITLE
Compiling with intel compiler fails

### ISSUE THREAD

**Issue by fTheobald** [LLNL/hypre#41]
Hello,

I tried to compile hypre with the Intel compiler. Unfortunately compiling fails due to an issue with the "xiar" tool from Intel, find attached the compiler output.

With GCC-7.3.0 everything seems fine. Is the Intel compiler not supported?

Thanks
Florian

[logfile.txt](https://github.com/LLNL/hypre/files/2495183/logfile.txt)

**Comment by liruipeng** [comment]
Hi, Florian,

The problem is on xiar.
You probably have AR=xiar. If you unset AR, and do your " ./configure --prefix=$(pwd)/../.. --without-MPI", hypre will set AR=ar -rcu, which should work fine.
But if you want to use xiar, set AR="xiar -qoffload-build rcu", and configure, it should also work.
You can check this in file config/Makefile.config

I tested on my end. Let me know if it does not work for you

Thanks

-RL

**Comment by fTheobald** [comment]
Hi Ruipeng,

You are correct. As I choose the Intel compiler the cluster sets AR=xiar. Tried unsetting AR and AR="xiar -qoffloading-build rcu".

Either way it compiles like a charm. Have many thanks!

Regards
Florian
