### ISSUE TITLE
Windows VisualStudio 2013 Compilation in Release

### ISSUE THREAD

**Issue by JCCobb** [LLNL/hypre#7]
I have been using this library for the past year, and it is really amazing! Congrats.
There is one issue that came up right at the beginning. I have to compile the code in windows (in linux it works fine with gcc) and I use visual studio for that. In debug mode everything is OK but when compiling in release mode (where the optimisations kick in) it seems to get completely stuck on "pfmg_relax.c". The optimisation option I use is maximise velocity, if I disable the optimisations it does compile. The only way of managing to overcome this problem is by using the intel compiler where it manages to compile the library with no hassle. But ideally I would need to compile the library using VisualStudio and not the intel compiler.
Thanks in advance.

**Comment by rfalgout** [comment]
This is a problem that we don't have an easy way to debug because we have an older version of VS (VS2012) that does not exhibit the problem.  We are discussing how best to support VS in the future, but haven't made any decisions yet.

Since it works in debug mode, try turning off optimization only for the problematic files.  For example, another user said the following worked for them (the file is different from yours):

  I had to disable optimization (/Od) on struct_ls/pfmg3_setup_rap.c for it to go through

Let us know if this approach works for you or if you find any other workarounds.  And thanks for the good words about the library!

**Comment by JCCobb** [comment]
Hi, thanks for the answer! It does seem odd that it manages to compile using the 2012 version and not the 2013 one.

Anyway, I have been trying the compilation on visual studio 2013. At first deactivating the optimisation for the file I commented it only passed the error to the next *.c file. So I tried disabling the optimisation to the "pfmg3_setup_rap.c" as the other user said and it worked!

So there must be something weird in this file that visual studio doesn't like...

Thanks very much for the support and keep up the amazing work!!
Jonathan.

**Comment by JCCobb** [comment]
Just wanted to add one last thing to this issue, it might help other people who, like me, add the Hypre library to their project using cmake.
I ended up adding this line at practically the end of the main CMakeLists.txt file:

```
#Turn optimization off for this file
set_source_files_properties (lapack/dlamch.c PROPERTIES COMPILE_FLAGS -O0)

if (MSVC)
  add_definitions(-D_CRT_SECURE_NO_WARNINGS)
  #Fix issue with visual studio 2013
  set_source_files_properties(struct_ls/pfmg3_setup_rap.c PROPERTIES COMPILE_FLAGS -Od)
endif ()
```
Jonathan.

**Comment by rfalgout** [comment]
Hi Jonathan,

I added the pfmg3 file fix to the repo, so that should appear in future releases.  Good suggestion!

One question.  Why do you have the dash in '-O0' for dlamch.c and '-Od' for the pfmg3 file?  They should both be '/Od' from what I can tell from the MSVC docs.  This is what I've set them to in the repo.

-Rob

**Comment by JCCobb** [comment]
Hi Rob,

Perfect! 😄 

Well the dash in front of '-O0' from 'dlamch.c' was by default there (wasn't inserted by me). And the dash for '-Od' comes that I usually use dash when I define, for example, the preprocessor definitions: in gcc we would define -D_preproc_definition but MSVC likes having them as /D_preproc_definition. I think cmake understands this and changes it depending on what compiler we are working on. Either way, as this fix is only for MSVC using the forward slash does seem to be the proper approach.

Jonathan.
